# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  site_name: Undercontrol.io
  noreply_email: noreply@undercontrol.io
  # TODO: admin_* can be cleaned up at some point
  admin_name: Undercontrol.io
  admin_username: undercontrol
  admin_email: admin@undercontrol.io
  admin_password: 12345678
  domain_name: localhost:3000
  email_provider_host: <%= ENV["SMTP_HOST"] %>
  email_provider_username: <%= ENV["SMTP_USERNAME"] %>
  email_provider_password: <%= ENV["SMTP_PASSWORD"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  secret_key_base: bf57d36c7859bf73e8306ec7b4f6925280871f8c78dc814028621d922bd50c088a15423561b61bd10b5aabab7122bd1d49d98f2578b75e0d5ecc93e99cf89da8

test:
  domain_name: example.com 
  secret_key_base: fe3fa7d8bf035fb1c4343b60f29f6797dee5aa7c3c49eb7c47065c04b4c3bf81bf8dec5aa2622adf66ffc03007c9a9ee647b759bd72071935ad220513771e439

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  site_name: <%= ENV["SITE_NAME"] %>
  noreply_email: <%= ENV["NOREPLY_EMAIL"] %>
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_username: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_NAME"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %> 
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %> 
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %> 
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %> 
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
